/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework03

import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

fun main(vararg args: String) = runBlocking {
    if (args.isEmpty()) {
        println("Command line should contain names of subReddits")
    } else {
        for (word in args) {
            launch {
                RedditClient().parse(word)
            }
        }
    }
}
